% function waveform = FiveGuys_downlink_waveform_single_user()

    carrier = nrSCSCarrierConfig('NSizeGrid',100);
    bwp = nrWavegenBWPConfig('NStartBWP',carrier.NStartGrid+10);
    ssb = nrWavegenSSBurstConfig('BlockPattern','Case A');
    pdcch = nrWavegenPDCCHConfig('AggregationLevel',2,'AllocatedCandidate',4);
    coreset = nrCORESETConfig;
    coreset.FrequencyResources = [1 1 1 1];
    coreset.Duration = 3;
    ss = nrSearchSpaceConfig;
    ss.NumCandidates = [8 4 0 0 0];
    pdsch = nrWavegenPDSCHConfig( ...
        'Modulation','16QAM','TargetCodeRate',658/1024,'EnablePTRS',true);
    dmrs = nrPDSCHDMRSConfig('DMRSTypeAPosition',3);
    pdsch.DMRS = dmrs;
    ptrs = nrPDSCHPTRSConfig('TimeDensity',2);
    pdsch.PTRS = ptrs;
    csirs = nrWavegenCSIRSConfig('RowNumber',4,'RBOffset',10,'NumRB',10,'SymbolLocations',5);
    cfgDL = nrDLCarrierConfig( ...
        'FrequencyRange','FR1', ...
        'ChannelBandwidth',40, ...
        'NumSubframes',20, ...
        'SCSCarriers',{carrier}, ...
        'BandwidthParts',{bwp}, ...
        'SSBurst',ssb, ...
        'CORESET',{coreset}, ...
        'SearchSpaces',{ss}, ...
        'PDCCH',{pdcch}, ...
        'PDSCH',{pdsch}, ...
        'CSIRS',{csirs});
    [waveform, info] = nrWaveformGenerator(cfgDL);

% end